### ISSUE TITLE
_collect_cpu_metadata (ppc)

### ISSUE THREAD

**Issue by planrich** [haypo/perf#11]
I'm currently trying to benchmark numpy operations on pypy (arch ppc64le, which is probably not supported right now). It seems as if the implementation to gather _collect_cpu_metadata does not work for ppc.

Here is what I found:

Spawned process fails to make a set out of an integer. (Line ~256, _collect_cpu_freq in perf/metadata.py). _get_logical_cpu_count returns an integer. Unsure what all_cpus should be.

**Comment by haypo** [comment]
Hi. Can you please check if the commit 35493139f897e811ea155d23fc507e0c90f3f1df fixed your issue?

**Comment by haypo** [comment]
I'm also interested to know if perf is able to retrieve metadata about your CPUs on ppc64le. On Intel, this is the kind of metadata which are retrieved:

```
haypo@selma$ python3 -m perf metadata|grep cpu
- cpu_config: 0-3=driver:intel_pstate, intel_pstate:turbo, governor:powersave
- cpu_count: 4
- cpu_freq: 0=1456 MHz, 1=2475 MHz, 2=2418 MHz, 3=2238 MHz
- cpu_model_name: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
- cpu_temp: coretemp:Physical id 0=50 C, coretemp:Core 0=48 C, coretemp:Core 1=50 C
```

**Comment by planrich** [comment]
Thx that solves the issue for the CPU count.

It is not able to extract meta data (sadly). Here is my commit to get around that:
https://github.com/planrich/perf/commit/08e717857b7f72f393c4e10ae5074396ec812765
(see the first two lines)

Here is the stack trace in the other case:

```
Traceback (most recent call last):
  File "/home/plan_rich/pypy-nightly/lib-python/2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/plan_rich/pypy-nightly/lib-python/2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/plan_rich/src/perf/perf/__main__.py", line 704, in <module>
    main()
  File "/home/plan_rich/src/perf/perf/__main__.py", line 696, in main
    func()
  File "/home/plan_rich/src/perf/perf/__main__.py", line 278, in cmd_metadata
    perf_metadata._collect_metadata(metadata)
  File "/home/plan_rich/src/perf/perf/metadata.py", line 415, in _collect_metadata
    _collect_cpu_metadata(metadata)
  File "/home/plan_rich/src/perf/perf/metadata.py", line 400, in _collect_cpu_metadata
    _collect_cpu_config(metadata, all_cpus)
  File "/home/plan_rich/src/perf/perf/metadata.py", line 316, in _collect_cpu_config
    config = _get_cpu_config(cpu)
  File "/home/plan_rich/src/perf/perf/metadata.py", line 295, in _get_cpu_config
    boost = _get_cpu_boost(cpu)
  File "/home/plan_rich/src/perf/perf/metadata.py", line 229, in _get_cpu_boost
    raise ValueError("unable to parse cpupower output: %r" % stdout)
ValueError: unable to parse cpupower output: 'analyzing CPU 0:\n  no or unknown cpufreq driver is active on this CPU\n'
```

After applying my two line changes (cpupower does not work properly on powerpc) I get this:

```
Metadata:
- aslr: Full randomization
- cpu_count: 160
- date: 2016-07-28T15:16:09
- hostname: gcc2-power8.osuosl.org
- load_avg_1min: 45.77
- mem_private: 76.7 MB
- mem_rss: 82.7 MB
- perf_version: 0.7.3
- platform: Linux-3.17.4-301.fc21.ppc64le-ppc64le-with-fedora-21-Twenty_One
- python_executable: /home/plan_rich/envpypy/bin/python
- python_implementation: pypy
- python_unicode: UCS-4
- python_version: 2.7.10 (64bit)
- timer: time.time()
```

**Comment by haypo** [comment]
Oh, non-working cpupower should be handled by the commit d5538b13fdb06dee41ba387df06db5c4480d250a.

It looks like perf fails to retrieve most information about your CPU, lacking metadata:

* cpu_config
* cpu_freq
* cpu_model_name
* cpu_temp

Can you please copy/paste the information of the first CPU from /proc/cpuinfo? There is no "model name" line?

Since you have 160 cores, it's maybe a bad idea to read the frequency and temperature of all CPUs :-D The output would just be too verbose.

**Comment by planrich** [comment]
It seems there is a model line

```
processor       : 0
cpu             : POWER8E (raw), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

...
< proc 1 - 158 same format as processor 0 but replace 0 with N >
...

processor       : 159
cpu             : POWER8E (raw), altivec supported
clock           : 3425.000000MHz
revision        : 2.1 (pvr 004b 0201)

timebase        : 512000000
platform        : PowerNV
model           : 8247-22L
machine         : PowerNV 8247-22L
firmware        : OPAL v3
```

**Comment by haypo** [comment]
> It seems there is a model line

Ok. The commit cf151dc42ea96a9d559cf0eb63f1612d03ca5876 should help to retrieve cpu_machine and cpu_freq.

For cpu_config: do you have /sys/devices/system/cpu/cpu0/cpufreq/ directory and /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor file? I'm surprised that you don't get cpu_config metadata.

**Comment by planrich** [comment]
Nope, it is not present on that machine. Here is the tree:

```
/sys/devices/system/cpu/cpu0
├── cache
│   ├── index0
│   │   ├── coherency_line_size
│   │   ├── level
│   │   ├── number_of_sets
│   │   ├── shared_cpu_map
│   │   ├── size
│   │   ├── type
│   │   └── ways_of_associativity
│   ├── index1
│   │   ├── coherency_line_size
│   │   ├── level
│   │   ├── number_of_sets
│   │   ├── shared_cpu_map
│   │   ├── size
│   │   ├── type
│   │   └── ways_of_associativity
│   ├── index2
│   │   ├── level
│   │   ├── number_of_sets
│   │   ├── shared_cpu_map
│   │   ├── size
│   │   └── type
│   └── index3
│       ├── level
│       ├── number_of_sets
│       ├── shared_cpu_map
│       ├── size
│       └── type
├── cpuidle
│   ├── state0
│   │   ├── desc
│   │   ├── disable
│   │   ├── latency
│   │   ├── name
│   │   ├── power
│   │   ├── residency
│   │   ├── time
│   │   └── usage
│   └── state1
│       ├── desc
│       ├── disable
│       ├── latency
│       ├── name
│       ├── power
│       ├── residency
│       ├── time
│       └── usage
├── crash_notes
├── crash_notes_size
├── dscr
├── mmcr0
├── mmcr1
├── mmcra
├── node0 -> ../../node/node0
├── online
├── physical_id
├── pir
├── pmc1
├── pmc2
├── pmc3
├── pmc4
├── pmc5
├── pmc6
├── power
│   ├── async
│   ├── autosuspend_delay_ms
│   ├── control
│   ├── runtime_active_kids
│   ├── runtime_active_time
│   ├── runtime_enabled
│   ├── runtime_status
│   ├── runtime_suspended_time
│   └── runtime_usage
├── purr
├── smt_snooze_delay
├── spurr
├── subsystem -> ../../../../bus/cpu
├── topology
│   ├── core_id
│   ├── core_siblings
│   ├── core_siblings_list
│   ├── physical_package_id
│   ├── thread_siblings
│   └── thread_siblings_list
└── uevent
```

**Comment by mahmoud** [comment]
fwiw this is not just a ppc problem. This affects the current PyPI version (0.7.2, 2016-07-21) for Linux x86/x86-64 Python 2.7.

**Comment by haypo** [comment]
@mahmoud : "fwiw this is not just a ppc problem. This affects the current PyPI version (0.7.2, 2016-07-21) for Linux x86/x86-64 Python 2.7."

Oh. What is your error message? Do you have psutil installed? Does the development version (git master branch) works for me? Can you paste the output of "$ python2 -m perf metadata|grep cpu" (especially for the master branch).

**Comment by mahmoud** [comment]
I'm referring to the pip installable version. Here it is being installed into a fresh env on Ubuntu 16.04 x86_64 Python 2.7.11:

```
mahmoud:~$ mktmpenv
New python executable in /home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/bin/python
Installing setuptools, pip, wheel...pip instaldone.
lvirtualenvwrapper.user_scripts creating /home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/bin/preactivate
virtualenvwrapper.user_scripts creating /home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/bin/postactivate
virtualenvwrapper.user_scripts creating /home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.
(tmp-fab871af6c2f8e51) mahmoud@:~/virtualenvs/tmp-fab871af6c2f8e51$ pip install perf
Collecting perf
Collecting six (from perf)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting statistics (from perf)
Collecting docutils>=0.3 (from statistics->perf)
Installing collected packages: six, docutils, statistics, perf
Successfully installed docutils-0.12 perf-0.7.2 six-1.10.0 statistics-1.0.3.5
(tmp-fab871af6c2f8e51) mahmoud:~/virtualenvs/tmp-fab871af6c2f8e51$ python -m perf timeit "x = 0"
Traceback (most recent call last):
  File "/home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/local/lib/python2.7/site-packages/perf/_timeit.py", line 71, in main
    runner.bench_sample_func(sample_func, timer)
  File "/home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/local/lib/python2.7/site-packages/perf/text_runner.py", line 673, in bench_sample_func
    return self._main(wrap_sample_func)
  File "/home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/local/lib/python2.7/site-packages/perf/text_runner.py", line 650, in _main
    return self._worker(bench, sample_func)
  File "/home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/local/lib/python2.7/site-packages/perf/text_runner.py", line 633, in _worker
    run = perf.Run(samples, warmups=warmups, metadata=metadata)
  File "/home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/local/lib/python2.7/site-packages/perf/__init__.py", line 217, in __init__
    perf_metadata._collect_metadata(metadata2)
  File "/home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/local/lib/python2.7/site-packages/perf/metadata.py", line 390, in _collect_metadata
    _collect_cpu_metadata(metadata)
  File "/home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/local/lib/python2.7/site-packages/perf/metadata.py", line 375, in _collect_cpu_metadata
    _collect_cpu_freq(metadata, all_cpus)
  File "/home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/local/lib/python2.7/site-packages/perf/metadata.py", line 232, in _collect_cpu_freq
    cpus = set(cpus)
TypeError: 'int' object is not iterable
Traceback (most recent call last):
  File "/home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/local/lib/python2.7/site-packages/perf/_timeit.py", line 71, in main
    runner.bench_sample_func(sample_func, timer)
  File "/home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/local/lib/python2.7/site-packages/perf/text_runner.py", line 673, in bench_sample_func
    return self._main(wrap_sample_func)
  File "/home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/local/lib/python2.7/site-packages/perf/text_runner.py", line 652, in _main
    return self._spawn_workers(bench)
  File "/home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/local/lib/python2.7/site-packages/perf/text_runner.py", line 779, in _spawn_workers
    run_suite = self._spawn_worker()
  File "/home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/local/lib/python2.7/site-packages/perf/text_runner.py", line 732, in _spawn_worker
    return _bench_suite_from_subprocess(args)
  File "/home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/local/lib/python2.7/site-packages/perf/text_runner.py", line 46, in _bench_suite_from_subprocess
    % (args[0], proc.returncode))
RuntimeError: /home/mahmoud/virtualenvs/tmp-fab871af6c2f8e51/bin/python failed with exit code 1
```
Installing psutil does fix the issue. Perhaps psutil should be a dependency? But really there's something else going on here. `cpus` is an `int` being passed to a `set`, that's never right.

**Comment by haypo** [comment]
Since perf 0.7.4 was released with various bugfixes and support for ppc64le, can we now close this issue?

**Comment by mahmoud** [comment]
This fixed the issue on my and my coworker's Linux machines.

**Comment by planrich** [comment]
Yes, thanks for the changes!
