### ISSUE TITLE
Support PyPy?

### ISSUE THREAD

**Issue by Tinche** [haypo/perf#12]
Using PyPy 5.3.1:

```
> pyperf timeit ""
Traceback (most recent call last):
  File "/home/tin/pg/attrs/.venv-pypy/site-packages/perf/_timeit.py", line 71, in main
    runner.bench_sample_func(sample_func, timer)
  File "/home/tin/pg/attrs/.venv-pypy/site-packages/perf/text_runner.py", line 719, in bench_sample_func
    return self._main(wrap_sample_func)
  File "/home/tin/pg/attrs/.venv-pypy/site-packages/perf/text_runner.py", line 696, in _main
    return self._worker(bench, sample_func)
  File "/home/tin/pg/attrs/.venv-pypy/site-packages/perf/text_runner.py", line 634, in _worker
    raw_sample = sample_func(loops)
  File "/home/tin/pg/attrs/.venv-pypy/site-packages/perf/text_runner.py", line 717, in wrap_sample_func
    return sample_func(loops, *args)
  File "/home/tin/pg/attrs/.venv-pypy/site-packages/perf/_timeit.py", line 55, in sample_func
    return timer.inner(it, timer.timer)
AttributeError: Timer instance has no attribute 'inner'
Traceback (most recent call last):
  File "/home/tin/pg/attrs/.venv-pypy/site-packages/perf/_timeit.py", line 71, in main
    runner.bench_sample_func(sample_func, timer)
  File "/home/tin/pg/attrs/.venv-pypy/site-packages/perf/text_runner.py", line 719, in bench_sample_func
    return self._main(wrap_sample_func)
  File "/home/tin/pg/attrs/.venv-pypy/site-packages/perf/text_runner.py", line 698, in _main
    return self._spawn_workers(bench)
  File "/home/tin/pg/attrs/.venv-pypy/site-packages/perf/text_runner.py", line 830, in _spawn_workers
    run_suite = self._spawn_worker()
  File "/home/tin/pg/attrs/.venv-pypy/site-packages/perf/text_runner.py", line 783, in _spawn_worker
    return _bench_suite_from_subprocess(cmd)
  File "/home/tin/pg/attrs/.venv-pypy/site-packages/perf/text_runner.py", line 46, in _bench_suite_from_subprocess
    % (args[0], proc.returncode))
RuntimeError: /home/tin/pg/attrs/.venv-pypy/bin/pypy failed with exit code 1
```

Can anything be done?

**Comment by haypo** [comment]
Ah, it looks like timeit.Timer.inner() doesn't exist on PyPy. It shouldn't
be hard to support PyPy in perf.timeit.

**Comment by haypo** [comment]
perf 0.7.4 (released at 2018-08-18) added PyPy support. PyPy is now tested by tox and Travis.

Thanks for your bug report!

**Comment by Tinche** [comment]
Awesome!
